routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['as' => "articles::", 'prefix' => 'articles'], function () {
    Route::get('/', "ArticleController@articles")->name('all');
    Route::get('/{id}/{slug?}', "ArticleController@show")->name('show');
    Route::get('/categories/{id}/{slug?}', "ArticleController@articleByCategory")->name('article-by-category');
});

Route::group(['prefix' => 'admin', 'as' => 'admin::', 'namespace' => 'Admin', 'middleware' => 'auth'], function () {

    Route::get('/', "HomeController@index")->name('home');

    Route::group(['prefix' => 'articles', 'as' => 'articles::', 'namespace' => null], function () {

        Route::get('/', "ArticleController@index")->name('all');
        Route::get('/new', "ArticleController@newArticle")->name('new');
        Route::post('/new', "ArticleController@createArticle")->name('create');
        Route::get('/edit/{id}', "ArticleController@editArticle")->name('edit');
        Route::post('/edit/{id}', "ArticleController@updateArticle")->name('update');
        Route::delete('/delete/{id}', "ArticleController@deleteArticle")->name('delete');

    });

    Route::group(['prefix' => 'categories', 'as' => 'categories::'], function () {

        Route::get('/', "CategoryController@index")->name('all');
        Route::get('/new', "CategoryController@create")->name('new');
        Route::post('/new', "CategoryController@store")->name('create');
        Route::get('/edit/{category}', "CategoryController@edit")->name('edit');
        Route::post('/edit/{category}', "CategoryController@update")->name('update');
        Route::delete('/delete/{category}', "CategoryController@destroy")->name('destroy');

    });

    Route::group(['prefix' => 'users', 'as' => 'users::'], function () {

        Route::get('/', "UserController@index")->name('all');
        Route::get('/new', "UserController@create")->name('new');
        Route::post('/new', "UserController@store")->name('create');
        Route::get('/edit/{user}', "UserController@edit")->name('edit');
        Route::post('/edit/{user}', "UserController@update")->name('update');
        Route::delete('/delete/{user}', "UserController@destroy")->name('destroy');

    });

    Route::group(['prefix' => 'settings', 'as' => 'settings::'], function () {

        Route::get('/', "SettingController@index")->name('all');
        Route::post('/', "SettingController@store")->name('save');

    });

    Route::group(['prefix' => 'api', 'as' => 'api::', 'namespace' => 'Api'], function () {

        Route::post('/markdown/parse', "MarkdownParserController@parse")->name('markdown::parse');

    });

    Route::get('edit-profile', "ProfileController@edit")->name('edit-profile');
    Route::post('edit-profile', "ProfileController@update")->name('edit-profile::update');

});

app/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;
    use SoftDeletes;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'activated', 'admin'
    ];

    protected $attributes = [
        'activated' => false,
        'admin' => false,
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function articles()
    {
        return $this->hasMany(Article::class);
    }
}

app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;

use App\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::orderBy('id', 'desc')->withCount(['articles'])->paginate();

        return response()->view('admin.user.users', [
            'users' => $users,
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $user = new User();

        return response()->view('admin.user.user_form', [
            'user' => $user,
        ]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $user = User::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'password' => $request->input('password'),
            'admin' => $request->input('admin', false),
        ]);

        return redirect()->route('admin::users::all');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return response()->view('admin.user.user_form', [
            'user' => $user,
        ]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, User $user)
    {
        $user->name = $request->input('name');
        $user->email = $request->input('email');

        if (auth()->user()->admin)
        {
            $user->admin = $request->input('admin', false);
        }

        if ($request->filled('password'))
        {
            $user->password = \Hash::make($request->input('password'));
        }

        $user->activated = $request->input('activated', false);

        $user->save();

        return redirect()->route('admin::users::all');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\User $user
     * @return \Illuminate\Http\Response
     * @throws \Exception
     */
    public function destroy(User $user)
    {
        if ($user->admin && !auth()->user()->admin)
        {
            return redirect()->route('admin::users::all');
        }

        if ($user->id == auth()->id())
        {
            return redirect()->route('admin::users::all');
        }

        $user->delete();

        return redirect()->route('admin::users::all');
    }
}

resources/views/admin/user/user_form.blade.php
@extends('layouts.admin')

@section('title')
    @if($user->id)
    {{ __('Edit user :name', ['name' => $user->name]) }}
    @else
    {{ __('Add new user') }}
    @endif
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin::home') }}">{{ __('Admin Home') }}</a></li>
                    <li class="breadcrumb-item"><a href="{{ route('admin::users::all') }}">{{ __('Users') }}</a></li>
                    <li class="breadcrumb-item">@yield('title')</li>
                </ol>

                <div class="row">
                    <div class="col-6">
                        <form action="{{ $user->id ? route('admin::users::update', [$user]) : route('admin::users::create') }}" method="post">
                            @csrf

                            <div class="form-group">
                                <label>{{ __('Name') }}</label>
                                <input type="text" class="form-control" placeholder="{{ __('Name') }}" name="name" value="{{ $user->name }}">
                            </div>

                            <div class="form-group">
                                <label>{{ __('Email') }}</label>
                                <input type="text" class="form-control" placeholder="{{ __('Email') }}" name="email" value="{{ $user->email }}">
                            </div>

                            <div class="form-group">
                                <label>{{ __('Password') }}</label>
                                <input type="password" class="form-control" placeholder="{{ __('Password') }}" name="password">
                                @if($user->id)
                                    <div class="mt-2">
                                        <em class="text-muted">
                                            {{ __('Let it empty if you dont want to change the password') }}
                                        </em>
                                    </div>
                                @endif
                            </div>

                            <div class="form-group form-check">
                                <input type="checkbox" class="form-check-input" id="activated" name="activated" value="1" {{ $user->activated ? 'checked' : '' }}>
                                <label for="activated" class="form-check-label">{{ __('Activate account') }}</label>
                            </div>
                            <div class="mb-4">
                                <em class="text-muted">
                                    {{ __('Non activated account will not able to log in') }}
                                </em>
                            </div>

                            @if(auth()->user()->admin)
                                <div class="form-group form-check">
                                    <input type="checkbox" class="form-check-input" id="role" name="admin" value="1" {{ $user->admin ? 'checked' : '' }}>
                                    <label for="role" class="form-check-label">{{ __('Is admin?') }}</label>
                                </div>
                            @endif

                            <div class="form-group my-5">
                                <button class="btn btn-primary btn-lg">{{ __('Save') }}</button>
                            </div>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
@endsection

resources/views/admin/user/users.blade.php
@extends('layouts.admin')

@section('title')
    {{ __('Users') }}
@endsection

@section('content')
    <div class="container">
        <div class="row">
            <div class="col">

                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="{{ route('admin::home') }}">{{ __('Admin Home') }}</a></li>
                    <li class="breadcrumb-item">@yield('title')</li>
                </ol>

                <div class="my-2">
                    <a href="{{ route('admin::users::new') }}" class="btn btn-primary">Add User</a>
                </div>

                <table class="table">
                    <thead>
                    <tr>
                        <th>{{ __('Name') }}</th>
                        <th>{{ __('Activated') }}</th>
                        <th>{{ __('Articles') }}</th>
                        <th>{{ __('Role') }}</th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        <tr>
                            <td>{{ $user->name }}</td>
                            <td><span class="badge badge-success">{{ $user->activated ? 'Activated' : '' }}</span></td>
                            <td>{{ $user->articles_count }}</td>
                            <td>{{ $user->admin ? 'Admin' : 'User' }}</td>
                            <td>
                                <div class="btn-group btn-group-sm">
                                    <a href="{{ route('admin::users::edit', [$user]) }}" class="btn btn-link">{{ __('Edit') }}</a>
                                    <button class="btn btn-link text-danger" onclick="$('#delete-user-{{ $user->id }}').submit()">{{ __('Delete') }}</button>
                                </div>
                                <form action="{{ route('admin::users::destroy', [$user]) }}" class="hide" id="delete-user-{{ $user->id }}" method="post" onsubmit="return confirm('{{ __('Delete this item?') }}')">@csrf @method('delete')</form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>

                {!! $users->links() !!}
            </div>
        </div>
    </div>
@endsection